INSERT INTO product (product_id, price, name, description)
VALUES ('jenlooper-cactus', 500, 'The Quantified Cactus: An Easy Plant Soil Moisture Sensor',
        'This project is a good learning project to get comfortable with soldering and programming an Arduino.'),
       ('jenlooper-light', 500, 'A beautiful switch-on book light',
        'Use craft items you have around the house, plus two LEDs and a LilyPad battery holder, to create a useful book light for reading in the dark.'),
       ('jenlooper-lightshow', 500, 'Bling your Laptop with an Internet-Connected Light Show',
        'Create a web-connected light-strip API controllable from your website, using the Particle.io.'),
       ('jenlooper-survival', 500, 'Create a Compact Survival Kit with LED Track Lighting',
        'Use an Altoids tin with Chibitronics sticker LEDs to create a light-up compact that doubles as a survival kit for the young hipster'),
       ('sailorhg-bubblesortpic', 500, 'Bubblesort Visualization',
        'Visualization of sailor scouts sorted by bubblesort algorithm by their planet\u0027s distance from the sun'),
       ('sailorhg-corsage', 500, 'Light-up Corsage', 'Light-up corsage I made with my summer intern.'),
       ('sailorhg-kit', 500, 'Pastel hardware kit',
        'Pastel hardware kits complete with custom manufactured pastel alligator clips.'),
       ('sailorhg-led', 500, 'Heart-shaped LED', 'custom molded heart shaped LED with sprinkles.'),
       ('selinazawacki-soi-shirt', 500, 'Black Sweatshirt',
        'Black sweatshirt hoody with the Sick of the Internet logo.'),
       ('selinazawacki-soi-pins', 500, 'Sick of the Internet Pins',
        'Still some time to enter the pin/sticker giveaway! '),
       ('vogueandcode-hipster-dev-bro', 500, 'Hipster Dev',
        'Hipster Dev is busy coding away while styled in a camo jacket and orange beanie.'),
       ('vogueandcode-pretty-girls-code-tee', 500, 'Pretty Girls Code Tee',
        'Everyone\u2019s favorite design is finally here on a tee! The Pretty Girls Code crew-neck tee is available in a soft pink with red writing.'),
       ('vogueandcode-ruby-sis-2', 500, 'Ruby Sis',
        'Styled in a dashiki, Ruby Sis is listening to music while coding in her favorite language, Ruby!'),
       ('selinazawacki-moon', 500, 'Holographic Dark Moon Necklace',
        'Not sure if I\u0027ll be making more, get it while I have it in the store.'),
       ('selinazawacki-shirt', 500, 'Floppy Crop', 'Used up the Diskette fabric today to make 2 of these crops.'),

       ('jenlooper-cactus-lite', 200, 'The Quantified Cactus: An Easy Plant Soil Moisture Sensor',
        'This project is a good learning project to get comfortable with soldering and programming an Arduino.'),
       ('jenlooper-light-lite', 200, 'A beautiful switch-on book light',
        'Use craft items you have around the house, plus two LEDs and a LilyPad battery holder, to create a useful book light for reading in the dark.'),
       ('jenlooper-lightshow-lite', 200, 'Bling your Laptop with an Internet-Connected Light Show',
        'Create a web-connected light-strip API controllable from your website, using the Particle.io.'),
       ('jenlooper-survival-lite', 200, 'Create a Compact Survival Kit with LED Track Lighting',
        'Use an Altoids tin with Chibitronics sticker LEDs to create a light-up compact that doubles as a survival kit for the young hipster'),
       ('sailorhg-bubblesortpic-lite', 200, 'Bubblesort Visualization',
        'Visualization of sailor scouts sorted by bubblesort algorithm by their planet\u0027s distance from the sun'),
       ('sailorhg-corsage-lite', 200, 'Light-up Corsage', 'Light-up corsage I made with my summer intern.'),
       ('sailorhg-kit-lite', 200, 'Pastel hardware kit',
        'Pastel hardware kits complete with custom manufactured pastel alligator clips.'),
       ('sailorhg-led-lite', 200, 'Heart-shaped LED', 'custom molded heart shaped LED with sprinkles.'),
       ('selinazawacki-soi-shirt-lite', 200, 'Black Sweatshirt',
        'Black sweatshirt hoody with the Sick of the Internet logo.'),
       ('selinazawacki-soi-pins-lite', 200, 'Sick of the Internet Pins',
        'Still some time to enter the pin/sticker giveaway! '),
       ('vogueandcode-hipster-dev-bro-lite', 200, 'Hipster Dev',
        'Hipster Dev is busy coding away while styled in a camo jacket and orange beanie.'),
       ('vogueandcode-pretty-girls-code-tee-lite', 200, 'Pretty Girls Code Tee',
        'Everyone\u2019s favorite design is finally here on a tee! The Pretty Girls Code crew-neck tee is available in a soft pink with red writing.'),
       ('vogueandcode-ruby-sis-2-lite', 200, 'Ruby Sis',
        'Styled in a dashiki, Ruby Sis is listening to music while coding in her favorite language, Ruby!'),
       ('selinazawacki-moon-lite', 200, 'Holographic Dark Moon Necklace',
        'Not sure if I\u0027ll be making more, get it while I have it in the store.'),
       ('selinazawacki-shirt-lite', 200, 'Floppy Crop', 'Used up the Diskette fabric today to make 2 of these crops.'),

       ('jenlooper-cactus-max', 800, 'The Quantified Cactus: An Easy Plant Soil Moisture Sensor',
        'This project is a good learning project to get comfortable with soldering and programming an Arduino.'),
       ('jenlooper-light-max', 800, 'A beautiful switch-on book light',
        'Use craft items you have around the house, plus two LEDs and a LilyPad battery holder, to create a useful book light for reading in the dark.'),
       ('jenlooper-lightshow-max', 800, 'Bling your Laptop with an Internet-Connected Light Show',
        'Create a web-connected light-strip API controllable from your website, using the Particle.io.'),
       ('jenlooper-survival-max', 800, 'Create a Compact Survival Kit with LED Track Lighting',
        'Use an Altoids tin with Chibitronics sticker LEDs to create a light-up compact that doubles as a survival kit for the young hipster'),
       ('sailorhg-bubblesortpic-max', 800, 'Bubblesort Visualization',
        'Visualization of sailor scouts sorted by bubblesort algorithm by their planet\u0027s distance from the sun'),
       ('sailorhg-corsage-max', 800, 'Light-up Corsage', 'Light-up corsage I made with my summer intern.'),
       ('sailorhg-kit-max', 800, 'Pastel hardware kit',
        'Pastel hardware kits complete with custom manufactured pastel alligator clips.'),
       ('sailorhg-led-max', 800, 'Heart-shaped LED', 'custom molded heart shaped LED with sprinkles.'),
       ('selinazawacki-soi-shirt-max', 800, 'Black Sweatshirt',
        'Black sweatshirt hoody with the Sick of the Internet logo.'),
       ('selinazawacki-soi-pins-max', 800, 'Sick of the Internet Pins',
        'Still some time to enter the pin/sticker giveaway! '),
       ('vogueandcode-hipster-dev-bro-max', 800, 'Hipster Dev',
        'Hipster Dev is busy coding away while styled in a camo jacket and orange beanie.'),
       ('vogueandcode-pretty-girls-code-tee-max', 800, 'Pretty Girls Code Tee',
        'Everyone\u2019s favorite design is finally here on a tee! The Pretty Girls Code crew-neck tee is available in a soft pink with red writing.'),
       ('vogueandcode-ruby-sis-2-max', 800, 'Ruby Sis',
        'Styled in a dashiki, Ruby Sis is listening to music while coding in her favorite language, Ruby!'),
       ('selinazawacki-moon-max', 800, 'Holographic Dark Moon Necklace',
        'Not sure if I\u0027ll be making more, get it while I have it in the store.'),
       ('selinazawacki-shirt-max', 800, 'Floppy Crop', 'Used up the Diskette fabric today to make 2 of these crops.'),

       ('jenlooper-cactus-pro', 1800, 'The Quantified Cactus: An Easy Plant Soil Moisture Sensor',
        'This project is a good learning project to get comfortable with soldering and programming an Arduino.'),
       ('jenlooper-light-pro', 1800, 'A beautiful switch-on book light',
        'Use craft items you have around the house, plus two LEDs and a LilyPad battery holder, to create a useful book light for reading in the dark.'),
       ('jenlooper-lightshow-pro', 1800, 'Bling your Laptop with an Internet-Connected Light Show',
        'Create a web-connected light-strip API controllable from your website, using the Particle.io.'),
       ('jenlooper-survival-pro', 1800, 'Create a Compact Survival Kit with LED Track Lighting',
        'Use an Altoids tin with Chibitronics sticker LEDs to create a light-up compact that doubles as a survival kit for the young hipster'),
       ('sailorhg-bubblesortpic-pro', 1800, 'Bubblesort Visualization',
        'Visualization of sailor scouts sorted by bubblesort algorithm by their planet\u0027s distance from the sun'),
       ('sailorhg-corsage-pro', 1800, 'Light-up Corsage', 'Light-up corsage I made with my summer intern.'),
       ('sailorhg-kit-pro', 1800, 'Pastel hardware kit',
        'Pastel hardware kits complete with custom manufactured pastel alligator clips.'),
       ('sailorhg-led-pro', 1800, 'Heart-shaped LED', 'custom molded heart shaped LED with sprinkles.'),
       ('selinazawacki-soi-shirt-pro', 1800, 'Black Sweatshirt',
        'Black sweatshirt hoody with the Sick of the Internet logo.'),
       ('selinazawacki-soi-pins-pro', 1800, 'Sick of the Internet Pins',
        'Still some time to enter the pin/sticker giveaway! '),
       ('vogueandcode-hipster-dev-bro-pro', 1800, 'Hipster Dev',
        'Hipster Dev is busy coding away while styled in a camo jacket and orange beanie.'),
       ('vogueandcode-pretty-girls-code-tee-pro', 1800, 'Pretty Girls Code Tee',
        'Everyone\u2019s favorite design is finally here on a tee! The Pretty Girls Code crew-neck tee is available in a soft pink with red writing.'),
       ('vogueandcode-ruby-sis-2-pro', 1800, 'Ruby Sis',
        'Styled in a dashiki, Ruby Sis is listening to music while coding in her favorite language, Ruby!'),
       ('selinazawacki-moon-pro', 1800, 'Holographic Dark Moon Necklace',
        'Not sure if I\u0027ll be making more, get it while I have it in the store.'),
       ('selinazawacki-shirt-pro', 1800, 'Floppy Crop', 'Used up the Diskette fabric today to make 2 of these crops.');





